### ISSUE TITLE
Unhandled Exception

### ISSUE THREAD

**Issue by NULLx76** [Brqqq/SpotifyLyricsGrabber#2]
When I start the application I alway get an unhandled exception error, see below for image and error log.

![image](https://cloud.githubusercontent.com/assets/1809198/23769120/98a3b026-050e-11e7-8592-f58755182c71.png)
[log.txt](https://github.com/Brqqq/SpotifyLyricsGrabber/files/832208/log.txt)

**Comment by Brqqq** [comment]
I have added a new release to fix this. 

It was caused by an outdated SpotifyApi. If you're building from source, make sure it redownloads the NuGet packages

**Comment by NULLx76** [comment]
Works perfectly now, thanks!
